export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const CHANGE_MODAL = 'CHANGE_MODAL';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
